### ISSUE TITLE
About Wazirx_Bot

### ISSUE THREAD

**Issue by vnk31** [arnabm14/WazirX_Crypto_Trading_Bot#1]
Hi arnab this nirmal, wazirx Bot will be usefull for many of them. Pls if u have a video how to deploy or any other video link to run the program, pls mention the link it will be helpful to me and my friends. Waiting for your replay.

**Comment by arnabm14** [comment]
This is for educational purposes and individual models to train. This is not an Algorithmic trading bot. If you are looking for that, follow this post :

https://www.linkedin.com/feed/update/urn:li:activity:6860246034174611456/
